version: '3.8'

services:
  blockchain-hotswap:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALCHEMY_URL=${ALCHEMY_URL}
      - CHAINSTACK_URL=${CHAINSTACK_URL}
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped